[package]
name = "example-skim-navi"
version = "0.0.1"
edition = "2021"

[dependencies]
regex = "1.7.1"
reqwest = { version = "0.11.11", features = ["stream"] }
tokio = { version = "1.37.0", features = ["full"] }
warpy = "0.2.3"
skim-navi = { path = "../" }
